# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_p101_sync_pthread
    test_fault_wrappers_p101_sync_semaphore
    test_fault_wrappers_p101_thread_pthread
    test_fault_wrappers_p101_thread_signal
)
